find_bits: find_bits.o calculation.o
	gcc -Wall -ansi -pedantic calculation.o find_bits.o -o find_bits
find_bits.o: find_bits.c 
	gcc -c -Wall -ansi -pedantic -o find_bits.o find_bits.c 
calculation.o: calculation.c 
	gcc -c -Wall -ansi -pedantic -o calculation.o calculation.c 
