my_scalar: my_scalar.o calculation.o
	gcc -Wall -ansi -pedantic my_scalar.o calculation.o -o my_scalar
my_scalar.o: my_scalar.c 
	gcc -c -Wall -ansi -pedantic -o my_scalar.o my_scalar.c 
calculation.o: calculation.c 
	gcc -c -Wall -ansi -pedantic -o calculation.o calculation.c 
